spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Messenger
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: flase
        format_sql: true

  h2:
    console:
      enabled=true:

  rabbitmq:
    host: 52.79.203.88
    port: 5672
    username: root
    password: password

  session:
    store-type: jdbc
  profiles:
    active: local
    include:
      - aws
      - credentials
my :
  tempFilePath : src/main/resources/

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

fcm:
  tempFilePath : reliablemessage-168d1-firebase-adminsdk-olyui-caec3e6e5f.json

--- # dev 환경
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info

server:
  port: 8080
---

--- # prod 환경
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capston_design_db?useSSL=false&characterEncoding=UTF-8&serverTimeZone=UTC
    username: capston
    password: 1234cap
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

server:
  port: 8089

---