spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Messenger
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: flase
        format_sql: true

  h2:
    console:
      enabled=true:

  session:
    store-type: jdbc
  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

--- # dev 환경
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info

server:
  port: 8080
---

--- # prod 환경
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: info

server:
  port: 8089

---