spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Messenger
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: flase
        format_sql: true

  h2:
    console:
      enabled=true:

  session:
    store-type: jdbc
  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: knu-moapp2
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
      access-key: 1234
      secret-key: 1234

--- # dev 환경
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info

server:
  port: 8080
---

--- # prod 환경
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capston_design_db?useSSL=false&characterEncoding=UTF-8&serverTimeZone=UTC
    username: capston
    password: 1234cap
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

server:
  port: 8089

---